version: '2.1'

networks:
  monitoring:
    driver: bridge  # Definição corrigida

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "14250:14250"
      - "16686:16686"
    networks:
      - monitoring

  telemetry-collector:
    image: otel/opentelemetry-collector:latest
    container_name: telemetry-collector
    volumes:
      - ./opentelemetry-collector/otel-config.yaml:/etc/otel-config.yaml
    command: ["--config=/etc/otel-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "55679:55679"
    networks:
      - monitoring

  app-customer-services:
    build:
      context: ./applications/customer-service  # Caminho corrigido
      dockerfile: Dockerfile  
    container_name: app-customer-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - monitoring
    depends_on:
      - telemetry-collector

  app-tracing-node:
    build:
      context: ./applications/tracing-node
      dockerfile: Dockerfile
    container_name: app-tracing-node
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - monitoring
    depends_on:
      - telemetry-collector