version: "3.1"

networks:
  mysql-network:

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
  cadvisor:
      image: gcr.io/cadvisor/cadvisor
      volumes:
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      ports:
        - "8080:8080"      
      expose:
        - 8080
      networks:
        - mysql-network
  sync-mysql-sleep:
    image: ${IMAGEM}
    depends_on:
      - mysql-container
    ports:
      - "3000:3000"
    mem_limit: ${MEMORY_NODE}
    memswap_limit: ${MEMORY_NODE}
    networks:
      - mysql-network

volumes:
  mysql-data:
