version: "3.1"

networks:
  mysql-network:

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

  node-app:
    image: ${IMAGEM}
    depends_on:
      - mysql-container
    ports:
      - "3000:3000"
    mem_limit: 88m
    memswap_limit: 88m
    networks:
      - mysql-network

volumes:
  mysql-data:
