receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:  
  otlp:
    endpoint: "http://127.0.0.1:14250"  # Endereço do Jaeger (ajuste conforme seu ambiente)
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]