server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push # Certifique-se de que a URL corresponda à configuração do Loki no seu ambiente

scrape_configs:
  - job_name: logs
    static_configs:
      - targets:
          - localhost
    labels:
      job: myapp
      __path__: /var/log/tracegc/*.log # Substitua pelo caminho dos seus logs
