version: "3.1"
networks:
  networkall:
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}
    mysql-data: {}
services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:driver=local
    networks:
      - networkall
  cadvisor:
      image: gcr.io/cadvisor/cadvisor
      volumes:
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
      ports:
        - "8080:8080"      
      expose:
        - 8080
      networks:
        - networkall
  app:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGEM}
    depends_on:
      - mysql-container
    ports:
      - "7001:7001"
    mem_limit: ${MEMORY_NODE}
    memswap_limit: ${MEMORY_NODE}
    #cpus: 0.1
    networks:
      - networkall
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - networkall
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - networkall